### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by budingts** [hanks-zyh/Hrn#1]
我下载你这个项目怎么运行啊，怎么总是报错啊

**Comment by hanks-zyh** [comment]
@juanq123 运行前需要npm install 的，当然前提是react-Native环境配置好了，还有就是没有适配iOS

**Comment by budingts** [comment]
```
        android也是到处报错，可能失去不熟悉吧，麻烦了，我在试试发自网易邮箱大师
        在2016年02月04日 14:51，张玉涵 写道:@juanq123 运行前需要npm install 的，当然前提是react-Native环境配置好了，还有就是没有适配iOS
```

**Comment by budingts** [comment]
02-26 15:21:45.473 1615-1689/com.awesomeproject E/ReactNative: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
02-26 15:21:45.473 1615-1689/com.awesomeproject E/unknown:React: Exception in native call from JS
                                                                 com.facebook.react.bridge.JSExecutionException: ReferenceError: Can't find variable: __fbBatchedBridge (line 1 in the generated bundle)
                                                                     at com.facebook.react.bridge.ReactBridge.loadScriptFromAssets(Native Method)
                                                                     at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
                                                                     at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:154)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
                                                                     at java.lang.Thread.run(Thread.java:841)

这个错误怎么解决

**Comment by budingts** [comment]
项目下载完了，是不是现在对应目录下，运行 npm install ，然后还要再运行 react-native start

**Comment by feiyangwei** [comment]
我也出现这个问题了，重新reload后，提示“unable to download js bundle”

**Comment by hanks-zyh** [comment]
我这个时间有点久了，建议去看新版本的文档
